/* empty css                      */import{a as q,S as v,i as c}from"./assets/vendor-B5nsgUv9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const M="54668124-f075674b72691b434b6dd74f8",B="https://pixabay.com/api/";async function p(r,o){return(await q.get(B,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const g=document.querySelector(".gallery"),m=document.querySelector(".loader"),d=document.querySelector(".load-more"),R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const o=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:i,comments:P,downloads:S})=>`
<li class="gallery-item">
  <a href="${s}">
    <img src="${a}" alt="${e}" loading="lazy" />
  </a>
  <div class="info">
    <p><b>Likes</b> ${t}</p>
    <p><b>Views</b> ${i}</p>
    <p><b>Comments</b> ${P}</p>
    <p><b>Downloads</b> ${S}</p>
  </div>
</li>`).join("");g.insertAdjacentHTML("beforeend",o),R.refresh()}function $(){g.innerHTML=""}function y(){m.classList.remove("is-hidden")}function b(){m.classList.add("is-hidden")}function E(){d.classList.remove("is-hidden")}function u(){d.classList.add("is-hidden")}function O(){d.disabled=!0}function L(){d.disabled=!1}const x=document.querySelector(".form"),A=document.querySelector(".load-more");let n=1,f="",l=0;const w=15;x.addEventListener("submit",async r=>{r.preventDefault();const o=r.currentTarget.elements["search-text"].value.trim();if(!o){c.warning({message:"Please enter a search query!",position:"topRight"});return}f=o,n=1,l=0,$(),u(),y();try{const a=await p(f,n);if(l=a.totalHits,a.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(a.hits);const s=Math.ceil(l/w);n<s?(E(),L()):u()}catch{c.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{b()}});A.addEventListener("click",async()=>{O(),y(),n+=1;try{const r=await p(f,n);h(r.hits);const o=Math.ceil(l/w);n>=o?(u(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L();const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}catch{c.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
