/* empty css                      */import{a as q,S as M,i}from"./assets/vendor-B5nsgUv9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const R="54668124-f075674b72691b434b6dd74f8",B="https://pixabay.com/api/";async function g(s,o){return(await q.get(B,{params:{key:R,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),$=new M(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const o=s.map(({webformatURL:r,largeImageURL:a,tags:e,likes:t,views:n,comments:S,downloads:v})=>`
<li class="gallery-item">
  <a href="${a}">
    <img src="${r}" alt="${e}" loading="lazy" />
  </a>
  <div class="info">
    <p><b>Likes</b> ${t}</p>
    <p><b>Views</b> ${n}</p>
    <p><b>Comments</b> ${S}</p>
    <p><b>Downloads</b> ${v}</p>
  </div>
</li>`).join("");h.insertAdjacentHTML("beforeend",o),$.refresh()}function E(){h.innerHTML=""}function b(){p.classList.remove("is-hidden")}function L(){p.classList.add("is-hidden")}function w(){m.classList.remove("is-hidden")}function d(){m.classList.add("is-hidden")}const O=document.querySelector(".form"),u=document.querySelector(".load-more");let f="",c=1,l=0;const P=15;O.addEventListener("submit",async s=>{s.preventDefault();const o=s.currentTarget.elements["search-text"].value.trim();if(!o){i.warning({message:"Please enter a search query!",position:"topRight"});return}f=o,c=1,l=0,E(),d(),b();try{const r=await g(f,c);if(l=r.totalHits,r.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(r.hits),Math.ceil(l/P)===1?(i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d()):(w(),u.disabled=!1)}catch{i.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{L()}});u.addEventListener("click",async()=>{d(),b(),c+=1;try{const s=await g(f,c);y(s.hits);const o=Math.ceil(l/P);c>=o?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):(w(),u.disabled=!1);const r=document.querySelector(".gallery-item");if(r){const a=r.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}}catch{i.error({message:"Something went wrong. Please try again!",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
